"""
SQLAlchemy ORM models — the complete data schema for the logistics system.
Every table maps to a real-world concept in supply-chain management.
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, Text, JSON, ForeignKey, Enum
)
from sqlalchemy.orm import relationship
import enum
from database.connection import Base


# ── Enums ──

class ShipmentStatus(str, enum.Enum):
    PENDING = "pending"
    IN_TRANSIT = "in_transit"
    DELIVERED = "delivered"
    DELAYED = "delayed"
    REROUTED = "rerouted"
    CANCELLED = "cancelled"


class RiskLevel(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ActionType(str, enum.Enum):
    REROUTE = "reroute"
    SWITCH_SUPPLIER = "switch_supplier"
    REBALANCE_STOCK = "rebalance_stock"
    CREATE_PO = "create_purchase_order"
    ALERT_ONLY = "alert_only"


class AlertSeverity(str, enum.Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


# ── Models ──

class Shipment(Base):
    """Core entity — a shipment moving through the supply chain."""
    __tablename__ = "shipments"

    id = Column(Integer, primary_key=True, index=True)
    tracking_id = Column(String(50), unique=True, index=True, nullable=False)
    origin = Column(String(200), nullable=False)
    destination = Column(String(200), nullable=False)
    origin_lat = Column(Float)
    origin_lng = Column(Float)
    dest_lat = Column(Float)
    dest_lng = Column(Float)
    current_lat = Column(Float)
    current_lng = Column(Float)
    status = Column(String(20), default=ShipmentStatus.PENDING)
    carrier = Column(String(100))
    weight_kg = Column(Float, default=0)
    value_usd = Column(Float, default=0)
    temperature = Column(Float)  # IoT sensor reading
    humidity = Column(Float)     # IoT sensor reading
    eta = Column(DateTime)
    actual_delivery = Column(DateTime)
    risk_score = Column(Integer, default=0)  # 0-100
    risk_level = Column(String(20), default=RiskLevel.LOW)
    carbon_kg = Column(Float, default=0)
    route_data = Column(JSON)  # Encoded route waypoints
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    alerts = relationship("Alert", back_populates="shipment", cascade="all, delete-orphan")
    actions = relationship("ActionLog", back_populates="shipment", cascade="all, delete-orphan")
    risk_history = relationship("RiskHistory", back_populates="shipment", cascade="all, delete-orphan")


class Supplier(Base):
    """Supplier scorecard — tracks reliability and performance metrics."""
    __tablename__ = "suppliers"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False)
    location = Column(String(200))
    lat = Column(Float)
    lng = Column(Float)
    reliability_score = Column(Float, default=85.0)  # 0-100
    lead_time_days = Column(Float, default=5.0)
    cost_rating = Column(Float, default=3.0)  # 1-5
    quality_rating = Column(Float, default=4.0)  # 1-5
    carbon_rating = Column(Float, default=3.0)  # 1-5
    total_orders = Column(Integer, default=0)
    on_time_deliveries = Column(Integer, default=0)
    defect_rate = Column(Float, default=0.02)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class Alert(Base):
    """Real-time alerts generated by the AI engine."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    shipment_id = Column(Integer, ForeignKey("shipments.id"), nullable=True)
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    severity = Column(String(20), default=AlertSeverity.INFO)
    category = Column(String(50))  # weather, traffic, supplier, demand
    is_read = Column(Boolean, default=False)
    is_resolved = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    shipment = relationship("Shipment", back_populates="alerts")


class ActionLog(Base):
    """Audit trail — every automated/manual action the system takes."""
    __tablename__ = "action_logs"

    id = Column(Integer, primary_key=True, index=True)
    shipment_id = Column(Integer, ForeignKey("shipments.id"), nullable=True)
    action_type = Column(String(30), nullable=False)
    description = Column(Text, nullable=False)
    reason = Column(Text)  # AI-generated explanation
    risk_score_before = Column(Integer)
    risk_score_after = Column(Integer)
    cost_impact_usd = Column(Float, default=0)
    carbon_impact_kg = Column(Float, default=0)
    auto_approved = Column(Boolean, default=False)
    success = Column(Boolean, default=True)
    extra_data = Column(JSON)  # renamed from 'metadata' (reserved in SQLAlchemy)
    created_at = Column(DateTime, default=datetime.utcnow)

    shipment = relationship("Shipment", back_populates="actions")


class RiskHistory(Base):
    """Time-series risk scores — used by the learning loop to track improvements."""
    __tablename__ = "risk_history"

    id = Column(Integer, primary_key=True, index=True)
    shipment_id = Column(Integer, ForeignKey("shipments.id"))
    risk_score = Column(Integer)
    risk_factors = Column(JSON)  # breakdown of what contributed
    timestamp = Column(DateTime, default=datetime.utcnow)

    shipment = relationship("Shipment", back_populates="risk_history")


class DemandForecast(Base):
    """AI-generated demand forecasts per product/region."""
    __tablename__ = "demand_forecasts"

    id = Column(Integer, primary_key=True, index=True)
    product_category = Column(String(100))
    region = Column(String(100))
    forecast_date = Column(DateTime)
    predicted_demand = Column(Float)
    confidence = Column(Float)  # 0-1
    actual_demand = Column(Float)  # filled later for learning loop
    model_version = Column(String(50))
    created_at = Column(DateTime, default=datetime.utcnow)


class Inventory(Base):
    """Current stock levels across warehouses."""
    __tablename__ = "inventory"

    id = Column(Integer, primary_key=True, index=True)
    warehouse_id = Column(String(50))
    warehouse_name = Column(String(200))
    product_category = Column(String(100))
    quantity = Column(Integer, default=0)
    reorder_point = Column(Integer, default=100)
    max_capacity = Column(Integer, default=1000)
    lat = Column(Float)
    lng = Column(Float)
    updated_at = Column(DateTime, default=datetime.utcnow)


class ChatHistory(Base):
    """Stores AI chat conversations for context."""
    __tablename__ = "chat_history"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(50), index=True)
    role = Column(String(20))  # user / assistant
    message = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


class UserPreferences(Base):
    """Stores user onboarding preferences for personalized dashboard."""
    __tablename__ = "user_preferences"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String(100), unique=True, index=True, default="default_user")
    company_type = Column(String(50))  # manufacturer, retailer, 3pl, distributor
    supply_chain_type = Column(String(50))  # international, regional, domestic
    regions = Column(JSON)  # list of region IDs: [na, eu, apac, latam, mea]
    locations = Column(JSON)  # {origins: [], destinations: [], suppliers: []}
    priorities = Column(JSON)  # list: [cost, speed, risk, sustainability]
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
